name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release Placeholder
        run: |
          echo "Release Started"
          echo "Version: ${GITHUB_SHA:0:7}"