name: Python Application
on:
  push:
    branches:
      - main
      - qa
      - dev
  pull_request:
    branches:
      - main
      - qa
      - dev
jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

          if [ -f requirements.txt ]; then
          pip install -r mini_project/requirements.txt
          fi

      - name: Run Tests with Pytest
        run: |
          pip install pytest
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest
